// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.10
// source: cmds/cmds.proto

package cmds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cmd1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cmd1) Reset() {
	*x = Cmd1{}
	mi := &file_cmds_cmds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cmd1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd1) ProtoMessage() {}

func (x *Cmd1) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_cmds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd1.ProtoReflect.Descriptor instead.
func (*Cmd1) Descriptor() ([]byte, []int) {
	return file_cmds_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *Cmd1) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

type Cmd2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Y             string                 `protobuf:"bytes,1,opt,name=Y,proto3" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cmd2) Reset() {
	*x = Cmd2{}
	mi := &file_cmds_cmds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cmd2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd2) ProtoMessage() {}

func (x *Cmd2) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_cmds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd2.ProtoReflect.Descriptor instead.
func (*Cmd2) Descriptor() ([]byte, []int) {
	return file_cmds_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *Cmd2) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

var File_cmds_cmds_proto protoreflect.FileDescriptor

const file_cmds_cmds_proto_rawDesc = "" +
	"\n" +
	"\x0fcmds/cmds.proto\x12\bprotobuf\"\x14\n" +
	"\x04Cmd1\x12\f\n" +
	"\x01X\x18\x01 \x01(\x03R\x01X\"\x14\n" +
	"\x04Cmd2\x12\f\n" +
	"\x01Y\x18\x01 \x01(\tR\x01YB.Z,github.com/cmd-stream/codec-protobuf-go/cmdsb\x06proto3"

var (
	file_cmds_cmds_proto_rawDescOnce sync.Once
	file_cmds_cmds_proto_rawDescData []byte
)

func file_cmds_cmds_proto_rawDescGZIP() []byte {
	file_cmds_cmds_proto_rawDescOnce.Do(func() {
		file_cmds_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmds_cmds_proto_rawDesc), len(file_cmds_cmds_proto_rawDesc)))
	})
	return file_cmds_cmds_proto_rawDescData
}

var file_cmds_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmds_cmds_proto_goTypes = []any{
	(*Cmd1)(nil), // 0: protobuf.Cmd1
	(*Cmd2)(nil), // 1: protobuf.Cmd2
}
var file_cmds_cmds_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmds_cmds_proto_init() }
func file_cmds_cmds_proto_init() {
	if File_cmds_cmds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmds_cmds_proto_rawDesc), len(file_cmds_cmds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmds_cmds_proto_goTypes,
		DependencyIndexes: file_cmds_cmds_proto_depIdxs,
		MessageInfos:      file_cmds_cmds_proto_msgTypes,
	}.Build()
	File_cmds_cmds_proto = out.File
	file_cmds_cmds_proto_goTypes = nil
	file_cmds_cmds_proto_depIdxs = nil
}
